# ç½‘ç«™åç§°
site_name: é»é»-Space
# ç½‘ç«™æè¿°
site_description: Test
# ç½‘ç«™ä½œè€…
site_author: é»é»
# ç‰ˆæƒä¿¡æ¯
copyright: ä¸è´Ÿå¦‚æ¥ä¸è´Ÿå¿ <a href="#__consent">| æ›´æ”¹ Cookie Settings</a>
# å­˜å‚¨åº“
repo_url: https://github.com/Palpitation-github/mkdocs
# å­˜å‚¨åº“åå­—
repo_name: Palpitation-github/mkdocs
# ç¼–è¾‘åœ°å€
edit_uri: edit/main/docs/
# ä¸»é¢˜é…ç½®
theme:
  # ä¸»é¢˜åç§°
  name: material
  # æ‰©å±•ä¸»é¢˜
  custom_dir: overrides
  # è¯­è¨€
  language: zh
  font:
    # æ–‡å­—å­—ä½“
    text: Zen Maru Gothic
    # ä»£ç å­—ä½“
    code: Fira Code
  # ç½‘ç«™æ ‡é¢˜å›¾æ ‡
  favicon: assets/images/favicon.png
  icon:
    # ç½‘ç«™å›¾æ ‡
    logo: fontawesome/solid/terminal
    # é¡µè„šçš„ä¸Šä¸€é¡µ
    previous: fontawesome/solid/rotate-left
    # é¡µè„šçš„ä¸‹ä¸€é¡µ
    next: fontawesome/solid/rotate-right
    # å­˜å‚¨åº“
    repo: fontawesome/brands/git-alt
    # æ ‡ç­¾
    # ç¼–è¾‘æ­¤é¡µ
    edit: material/pencil
    # æŸ¥çœ‹æºä»£ç 
    view: material/eye
    tag:
      cpp: material/language-cpp
      ja: material/language-java
      py: material/language-python
    # menu:
    # æ›´æ”¹è¯­è¨€
    # alternate:
    # æœç´¢
    # search:
    # å…±äº«æœç´¢
    # share:
    # é‡ç½®æœç´¢,å…³é—­å…¬å‘Š
    # close:
    # è¿”å›é¡¶éƒ¨
    # top:
    # åŠè¯«
    # admonition:
  # ç½‘ç«™æ˜æš—é£æ ¼
  palette:
    # è‡ªåŠ¨æ¨¡å¼
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: åˆ‡æ¢ä¸ºç™½å¤©æ¨¡å¼
    # ç™½å¤©æ¨¡å¼
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: åˆ‡æ¢ä¸ºå¤œæ™šæ¨¡å¼
    # å¤œæ™šæ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-4
        name: åˆ‡æ¢ä¸ºç³»ç»Ÿåå¥½
  # ç‰¹æ€§
  features:
    # å³æ—¶åŠ è½½
    - navigation.instant
    # é¢„å…ˆåŠ è½½
    - navigation.instant.prefetch
    # è¿›åº¦æŒ‡ç¤ºå™¨
    - navigation.instant.progress
    # åœ°å€æ é”šç‚¹è·Ÿè¸ª
    - navigation.tracking
    # å¯¼èˆªé€‰é¡¹å¡
    - navigation.tabs
    # è¿”å›é¡¶éƒ¨æŒ‰é’®
    - navigation.top
    # é€‰é¡¹å¡è·Ÿéš
    # - navigation.tabs.sticky
    # å·¦ä¾§è¾¹æ 
    - navigation.sections
    # å·¦ä¾§è¾¹æ å±•å¼€
    - navigation.expand
    # å¯¼èˆªä¿®å‰ª,100é¡µä»¥ä¸Šä½¿ç”¨
    # - navigation.prune
    # ç« èŠ‚ç´¢å¼•é¡µ
    - navigation.indexes
    # ä¾§è¾¹æ é”šç‚¹è·Ÿéš
    # é¡µè„š
    - navigation.footer
    - toc.follow
    # ç›®å½•é›†æˆå·¦ä¾§è¾¹æ 
    # - toc.integrate
    # æœç´¢å»ºè®®
    - search.suggest
    # æœç´¢çªå‡ºæ˜¾ç¤º
    - search.highlight
    # æœç´¢å…±äº«
    - search.share
    # æ ‡é¢˜è‡ªåŠ¨éšè—
    - header.autohide
    # å…³é—­é€šçŸ¥
    - announce.dismiss
    # é“¾æ¥å†…å®¹é€‰é¡¹å¡
    - content.tabs.link
    # ä»£ç å¤åˆ¶
    - content.code.copy
    # ç¼–è¾‘æ­¤é¡µé¢
    - content.action.edit
    # æŸ¥çœ‹æºä»£ç 
    - content.action.view
# é¢å¤–é…ç½®
extra:
  # ä¸»é¡µå›¾æ ‡è·³è½¬
  homepage: https://palpitation-github.github.io/mkdocs/
  # å‘ç”µé€šçŸ¥
  generator: false
  # ç¤¾äº¤
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Palpitation-github/
      name: é»é» on Github
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/93584254
      name: é»é» on Bilibili
    - icon: material/email
      link: mailto:<783401553@qq.com>
      name: é»é» on Tencent Email
  # cookieåŒæ„
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  # ç½‘ç«™åˆ†æ
  # analytics:
  #   # åé¦ˆ
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="www.783401553@qq.com" target="_blank" rel="noopener">feedback form</a>.
  # æ ‡ç­¾
  tags:
    C++: cpp
    Java: ja
    Python: py
# é¢å¤–css
extra_css:
  - stylesheets/extra.css
  # åŠ¨æ•ˆ
  - https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
# é¢å¤–js
extra_javascript:
  # - javascripts/extra.js
  # æ•°å­¦
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # æµ‹è¯• mermaid
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
# å¯¼èˆªé¡µ
nav:
  - index.md
  - ğŸ¨ Collections:
    - collections/index.md
    - Page 1: collections/page-1.md
    - Page 2: collections/page-2.md
  - ğŸ› ï¸ Tools:
    - tools/index.md
    - Page 1: tools/page-1.md
    - Page 2: tools/page-2.md
  - ğŸ“­ Numbers:
    - numbers/index.md
# æ’ä»¶é…ç½®
plugins:
  # éšç§
  # - privacy
  # æœç´¢
  - search:
      enabled: true
  # æ ‡ç­¾
  - tags:
      enabled: true
      # æ ‡ç­¾æ–‡ä»¶
      tags_file: tags.md
  # æ›´æ–°å’Œåˆ›å»ºæ–‡æ¡£æ—¥æœŸ
  - git-revision-date-localized:
      # åˆ›å»ºæ–‡æ¡£æ—¶é—´
      enable_creation_date: true
      # æ—¥æœŸæ ¼å¼
      type: date
  # æ–‡æ¡£è´¡çŒ®è€…
  - git-committers:
      # ä»“åº“
      repository: Palpitation-github/mkdocs
      # åˆ†æ”¯
      branch: main
# markdowné…ç½®
markdown_extensions:
  # è§£æç‰¹å®šé”®å€¼å¯¹
  - meta
  # ç¼©å†™
  - abbr
  # åŠè¯«
  - admonition
  # å±æ€§åˆ—è¡¨
  - attr_list
  # HTMLä¸­ç¼–å†™Markdown,å®ç°ç½‘æ ¼
  - md_in_html
  # å®šä¹‰åˆ—è¡¨
  - def_list
  # è„šæ³¨
  - footnotes
  # è¡¨
  - tables
  # å¼ºè°ƒ
  - pymdownx.betterem
  # æ’å…¥,æ ‡è®°,æ³¢æµªå·
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # æŒ‰é”®
  - pymdownx.keys
  # æ ‡æ³¨å¯æŠ˜å 
  - pymdownx.details
  # æ™ºèƒ½ç¬¦å·
  - pymdownx.smartsymbols
  # åµŒå…¥ä»»æ„å†…å®¹
  - pymdownx.snippets
  # æ˜¾ç¤ºæ·»åŠ åˆ é™¤å’Œæ›´æ–°
  - pymdownx.critic:
      mode: view
  # æ•°å­¦
  - pymdownx.arithmatex:
      generic: true
  # ä»»åŠ¡åˆ—è¡¨
  - pymdownx.tasklist:
      # å¤é€‰æ¡†æ ·å¼
      custom_checkbox: true
      # å¯ç‚¹å‡»
      clickable_checkbox: false
  # å†…è”ä»£ç å¿«
  - pymdownx.inlinehilite
  # ä»£ç é«˜äº®
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
      auto_title: true
      # æ˜¾ç¤ºè¡Œå·
      linenums: true
      # è¡Œå·æ ·å¼
      linenums_style: pymdownx-inline
      # è¡Œå·é”šç‚¹é“¾æ¥
      anchor_linenums: true
      line_spans: __span
  # é€‰é¡¹å¡ç‰‡
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  # è¶…çº§å›´æ 
  - pymdownx.superfences:
      # mermaidå›¾è¡¨
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # è¡¨æƒ…
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # ç›®å½•
  - toc:
      # âš“ï¸
      permalink: ğŸª
      # é”šç‚¹æç¤º
      permalink_title: Anchor link to this section for reference
      title: ğŸ“‚ ç›®å½•
      # ç›®å½•æ·±åº¦
      toc_depth: 3